name: diana
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.9
  - pip
  - mysqlclient
  - ipykernel
  - gdal
  - poppler
  - django
  - django-filter
  - djangorestframework
  - djangorestframework-gis
  - django-cors-headers
  - pyvips
  - gunicorn
  - psycopg2-binary
  - pip:
    - django-admin-interface
    - drf-generators
    - drf-dynamic-fields
    - django-cleanup
